CREATE DATABASE IF NOT EXISTS BDD
CHARACTER SET utf8mb4;

USE BDD;

CREATE TABLE Stock_Principal(
   ID_STOCK INT AUTO_INCREMENT,
   QTE_ART INT NOT NULL,
   PRIMARY KEY(ID_STOCK)
) ENGINE=InnoDB;

CREATE TABLE Employés(
   ID_EMPLOYE INT AUTO_INCREMENT,
   MDP_UTILISATEUR VARCHAR(50) NOT NULL,
   TYPE_UTILISATEUR VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID_EMPLOYE)
) ENGINE=InnoDB;

CREATE TABLE Clients(
   ID_CLIENT INT AUTO_INCREMENT,
   NOM_CLIENT VARCHAR(50) NOT NULL,
   PRENOM_CLIENT VARCHAR(50) NOT NULL,
   ADRESSE_CLIENT VARCHAR(50) NOT NULL,
   CP_CLIENT INT NOT NULL,
   VILLE_CLIENT VARCHAR(50) NOT NULL,
   TEL_CLIENT VARCHAR(10) NOT NULL,
   PRIMARY KEY(ID_CLIENT)
) ENGINE=InnoDB;

CREATE TABLE Commandes(
   ID_COMMANDE INT AUTO_INCREMENT,
   PRIX_COMMANDE DECIMAL(15,2) NOT NULL,
   STATUT_PAIEMENT VARCHAR(50) NOT NULL,
   STATUT_EXPEDITION VARCHAR(50) NOT NULL,
   DATE_COMMANDE DATETIME NOT NULL,
   ID_CLIENT INT NOT NULL,
   PRIMARY KEY(ID_COMMANDE),
   FOREIGN KEY(ID_CLIENT) REFERENCES Clients(ID_CLIENT)
) ENGINE=InnoDB;

CREATE TABLE Tickets(
   ID_TICKET INT AUTO_INCREMENT,
   DATE_TICKET DATETIME NOT NULL,
   MOTIF_TICKET VARCHAR(50) NOT NULL,
   NUM_COMMANDE INT NOT NULL,
   NUM_CLIENT INT NOT NULL,
   ID_EMPLOYE INT NOT NULL,
   ID_COMMANDE INT NOT NULL,
   PRIMARY KEY(ID_TICKET),
   FOREIGN KEY(ID_EMPLOYE) REFERENCES Employés(ID_EMPLOYE),
   FOREIGN KEY(ID_COMMANDE) REFERENCES Commandes(ID_COMMANDE)
) ENGINE=InnoDB;

CREATE TABLE Article(
   ID_ARTICLE INT AUTO_INCREMENT,
   LIBELLE_ART VARCHAR(50) NOT NULL,
   PRIX_ART DECIMAL(15,2) NOT NULL,
   COULEUR_ART VARCHAR(50) NOT NULL,
   GARANTIE_ART INT NOT NULL,
   ID_STOCK INT NOT NULL,
   PRIMARY KEY(ID_ARTICLE),
   FOREIGN KEY(ID_STOCK) REFERENCES Stock_Principal(ID_STOCK)
) ENGINE=InnoDB;

CREATE TABLE Ligne_Commande(
   ID_LIG_COM INT AUTO_INCREMENT,
   QTE_COMMANDE INT NOT NULL,
   ID_ARTICLE INT NOT NULL,
   ID_COMMANDE INT NOT NULL,
   PRIMARY KEY(ID_LIG_COM),
   FOREIGN KEY(ID_ARTICLE) REFERENCES Article(ID_ARTICLE),
   FOREIGN KEY(ID_COMMANDE) REFERENCES Commandes(ID_COMMANDE)
) ENGINE=InnoDB;

CREATE TABLE Retour_SAV(
   ID_RETOUR INT AUTO_INCREMENT,
   QTE_RETOUR INT NOT NULL,
   ID_TICKET INT NOT NULL,
   PRIMARY KEY(ID_RETOUR),
   FOREIGN KEY(ID_TICKET) REFERENCES Tickets(ID_TICKET)
) ENGINE=InnoDB;

CREATE TABLE Stock_Rebus(
   ID_REBUS INT AUTO_INCREMENT,
   QTE_ART INT NOT NULL,
   MOTIF_REBUS VARCHAR(50) NOT NULL,
   ID_RETOUR INT NOT NULL,
   PRIMARY KEY(ID_REBUS),
   FOREIGN KEY(ID_RETOUR) REFERENCES Retour_SAV(ID_RETOUR)
) ENGINE=InnoDB;

-- Création clients --

INSERT INTO `clients`(`NOM_CLIENT`, `PRENOM_CLIENT`, `ADRESSE_CLIENT`, `CP_CLIENT`, `VILLE_CLIENT`, `TEL_CLIENT`)
VALUES ('Terrieur','Alain','5 rue du coin','26260','Le Nord','0707070707');